ibmruntimes/ci-jenkins-pipelines

pipelines/build/common/build_base_file.groovy
Launch downstream build to create srpm package for a release.
Copy and archive its artifacts to the openjdk pipeline.
=> Add downstream job for RedHat source RPM package

pipelines/build/common/build_base_file.groovy
Launch SRPM build only if any Linux platforms are built.
Update build parameters.
=> Add conditional for SRPM package build

pipelines/build/common/build_base_file.groovy
Remove Linux platforms duplicates.
Refine artifacts filter for RPM packages
=> Filter Linux platforms for SRPM builds

pipelines/build/regeneration/build_pipeline_generator.groovy, pipelines/jobs/configurations/jdk16u.groovy
=> Disable jdk16 pipelines

pipelines/build/common/openjdk_build_pipeline.groovy
Extend release sign to AIX and Linux platforms.
=> Sign AIX and Linux releases

pipelines/build/common/openjdk_build_pipeline.groovy
=> Fix for statement for checksum files generation

pipelines/build/common/openjdk_build_pipeline.groovy
Set filter extensions to *.zip for Windows
=> Fix binary filter for sign build for Windows

pipelines/jobs/configurations/jdk18_pipeline_config.groovy
=> Fix configuration for jdk18 pipeline

pipelines/jobs/configurations/jdk17_pipeline_config.groovy
Fix configureArgs in aarch64LinuxIBM map.
=> Fix jdk17 pipeline configuration

pipelines/build/common/build_base_file.groovy
Fix publishName parsing for jdk8.
=> Fix version for RPM build parameters

pipelines/build/common/build_base_file.groovy
Add check for testDynamic as boolean.
=> Add check for testDynamic

pipelines/defaults.json
=> Enable Dynamic Parallel testing for many targets

pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Replace --enable-dtrace=auto with --enable-dtrace

pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Disable ccache on jdk17 AIX Certified edition

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
=> Update vendor url and vendor bug url 8/11/17

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
=> Remove ea flag from Linux Aarch64 jdk8/11 specs

pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Remove vendor-version-string from jdk17 specs

pipelines/build/common/build_base_file.groovy
Add downstream job to check if release packages are signed.
=> Add code sign verification

pipelines/build/common/openjdk_build_pipeline.groovy
Fix if condition for binary name.
=> Fix binary name for release builds

pipelines/build/common/openjdk_build_pipeline.groovy
Generate metadata files for *.rpm and *.sig files.
=> Add metadata files for all installers and signature files

pipelines/build/common/build_base_file.groovy, pipelines/build/common/create_job_from_template.groovy, pipelines/jobs/pipeline_job_template.groovy
Delete workspace before build.
Delete previous builds artifacts.
Refine srpm artifacts filter.
=> Add workspace clean up before build

pipelines/build/common/weekly_release_pipeline.groovy, pipelines/build/regeneration/build_pipeline_generator.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/weekly_release_pipeline_job_template.groovy
Enable sanity.functional testing for Semeru 11 & 17 OE nightly builds.
=> Enable nightly testing for Semeru OE

pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Fix xlinux jdk17 config for enabling jres

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
=> Disable ccache xlinux jdk11 Certified

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
=> Add aarch64 linux Certified Edition

pipelines/jobs/configurations/jdk11u.groovy
=> Add aarch64IBM to targetConfigurations

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
=> Fix CE spec for jdk11 aarch64 linux

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
This is what code reviews are for
=> Fix CE spec for jdk11 aarch64 linux again

pipelines/jobs/configurations/jdk18.groovy, pipelines/jobs/configurations/jdk18_pipeline_config.groovy
Also remove vendor-version-string from jdk18 specs.
=> Add Mac aarch64 to Semeru pipelines

pipelines/jobs/configurations/jdk18_pipeline_config.groovy
=> Enable jres for jdk18 OpenJ9

pipelines/jobs/configurations/jdk18_pipeline_config.groovy
=> Add ea flag to Mac Aarch64

pipelines/build/common/openjdk_build_pipeline.groovy
=> Sign mac tarball as well

pipelines/build/common/openjdk_build_pipeline.groovy
Infer vendor version from configure arguments and pass it to the
installer job.
=> Infer vendor version from configure arguments

pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Add amac to Semeru OE 11 & 17

pipelines/jobs/configurations/jdk18_pipeline_config.groovy
=> Remove ea flag from Aarch64 Linux jdk18

pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Add CE specs for Mac Aarch64 jdk11/17

pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
=> Add criu spec to jdk11 xlinux

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
=> Remove Open Edition arg from Mac Aarch jdk11 CE

pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Enable jres for jdk17 CE specs

pipelines/build/common/build_base_file.groovy
=> Don't add whitespace if no existing configure args

pipelines/jobs/configurations/jdk19.groovy, pipelines/jobs/configurations/jdk19_pipeline_config.groovy
Set build node labels, configuration arguments, enable jre.
Schedule builds.
=> Configure Semeru 19 pipelines

pipelines/build/common/build_base_file.groovy
Related adoptium/ci-jenkins-pipelines#306
=> Run on master or built-in

pipelines/jobs/configurations/jdk17u.groovy
=> Remove aarch64alpinelinux from build

pipelines/build/common/openjdk_build_pipeline.groovy
=> Increase Artifactory retention to at least 6 months

pipelines/build/common/openjdk_build_pipeline.groovy
=> Increase Artifactory retention to at least 9 months

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk18u_pipeline_config.groovy, pipelines/jobs/configurations/jdk19_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
jdk8,11,17,18,19
Also there is a dup entry for amac on jdk11.
Merge it into the existing one.
=> Update Mac compile boxes to macOS 10.15

pipelines/build/common/openjdk_build_pipeline.groovy
=> Fix sign_build after merge

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Enable default test list for amac CE specs

pipelines/jobs/configurations/jdk19_pipeline_config.groovy, pipelines/jobs/configurations/jdk20_pipeline_config.groovy
Related: runtimes/backlog/issues/860
=> Enable FIPS testing in JDK19 and JDK20

pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
Depends on: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/590
=> Enable FIPS testing for JDK8

pipelines/build/common/openjdk_build_pipeline.groovy
=> Add suffix _criu for CRIU test builds

pipelines/build/common/openjdk_build_pipeline.groovy
=> Fix file pattern for semeru msi jre copyArtifact

pipelines/build/common/openjdk_build_pipeline.groovy
It gets passed in with the Semeru value
=> Remove filter from buildWindowsInstaller

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
Issue adoptium/ci-jenkins-pipelines#17
=> Try adding dockerArg to resolve uid perm issue

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
related: runtimes/backlog/issues/915
=> Enable FIPS testing for plinux for JDK8, 11 and 17

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk19_pipeline_config.groovy
- OE, CE
- 11, 17, 19
- Note: Still using '--with-noncompressedrefs' flag
=> Remove ea flag from amac

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Look for rhel7 as well as cent7 for criu compiles

pipelines/build/common/openjdk_build_pipeline.groovy
=> Prepend buildInfo with sys-rt and printout buildInfo

pipelines/build/common/openjdk_build_pipeline.groovy
=> Remove print buildInfo and add comment

pipelines/build/common/create_job_from_template.groovy, pipelines/jobs/pipeline_job_template.groovy
=> Correct variable name for GIT_BRANCH

pipelines/jobs/pipeline_job_template.groovy
=> Undo BRANCH change from #105

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
=> Enable FIPS testing for zlinux for JDK8, 11 and 17

pipelines/build/common/openjdk_build_pipeline.groovy
Related: runtimes/backlog/issues/890
=> Enable functional tests in internal repo

pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk17u.groovy, pipelines/jobs/configurations/jdk18u.groovy, pipelines/jobs/configurations/jdk19.groovy, pipelines/jobs/configurations/jdk8u.groovy
11 - 6:00pm (EST)
8 - 6:30
17 - 7
18/19 - 7:30 (every other day)
=> Reschedule nightly builds earlier

pipelines/build/common/build_base_file.groovy
=> Revert a bad merge conflict.

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk19u_pipeline_config.groovy, pipelines/jobs/configurations/jdk20_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
=> Don't compile in Docker for plinux yet

pipelines/build/openjdk_pipeline.groovy
=> Add check for JDK_OPENJ9_BRANCH

pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Enable zlinux CRIU spec for jdk11,17

pipelines/jobs/configurations/jdk19u_pipeline_config.groovy
=> Try disabling ccache on alinux jdk19

pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
related: runtimes/backlog/issues/1011
=> enable dev.external on machines with podman

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk19u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
=> Move aix compiles to 7.2

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
related: runtimes/backlog/issues/1032
=> Disable fips tests on p/zLinux

pipelines/build/common/openjdk_build_pipeline.groovy
=> Switch Artifactory to public network

pipelines/build/common/openjdk_build_pipeline.groovy
Only trigger runUploadTestImage if the test pipeline contains dev.external on JDK11 and JDK17 xlinux
related: runtimes/backlog/issues/1037
=> Add runUploadTestImage() for CRIU

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
Tests have been moved to dev.external
=> Remove sanity.external from CRIU specs

pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk17u.groovy
=> Disable xlinux criu spec

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk19u_pipeline_config.groovy, pipelines/jobs/configurations/jdk20_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
related: runtimes/backlog/issues/1034
=> enable full functional and system test builds for FIPS in weekly

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk19u_pipeline_config.groovy, pipelines/jobs/configurations/jdk20_pipeline_config.groovy, pipelines/jobs/configurations/jdk21_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
Is enabled by default on x/p/z linux in all versions
=> Remove explicit jitserver enable option

pipelines/build/common/openjdk_build_pipeline.groovy
related: runtimes/backlog/issues/1037
https://github.com/adoptium/aqa-tests/pull/4406
=> Add additional CRIU create image tests

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
Until it is turned on by default in extensions
=> Enable criu on default plinux spec 11 17

pipelines/build/common/openjdk_build_pipeline.groovy
AIX signs in a different job.
Fixes #140
=> Only look for signing label on linux rpm

pipelines/build/common/openjdk_build_pipeline.groovy
- Resolves backlog/issues/1075
- Related : https://github.ibm.com/runtimes/infrastructure/issues/7494
- Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>
=> Update label: ci.geo.raleigh -> ci.geo.rtp

pipelines/defaults.json
Until after signing service can be migrated
Issue infra 7517
=> Temp disable signer

pipelines/defaults.json
Original reverted via Adopt 573
=> Disable dev.openjdk dev.system from weekly

pipelines/build/common/openjdk_build_pipeline.groovy
=> Remove nodeFilter line that was removed via Adopt 668

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
Related: infrastructure/issues/7968
=> reenable system test builds for FIPS

pipelines/build/common/openjdk_build_pipeline.groovy
related: https://github.com/adoptium/aqa-tests/issues/4580
=> Set LIGHT_WEIGHT_CHECKOUT to true

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk16u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk18u_pipeline_config.groovy, pipelines/jobs/configurations/jdk19u_pipeline_config.groovy, pipelines/jobs/configurations/jdk20u_pipeline_config.groovy, pipelines/jobs/configurations/jdk21_pipeline_config.groovy, pipelines/jobs/configurations/jdk22_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
change from osx to mac label
issue: issue: https://github.ibm.com/runtimes/infrastructure/issues/7907
=> Issue 7907

pipelines/build/dockerFiles/cuda.dockerfile
=> Update to Cuda 11.0.3

pipelines/build/common/openjdk_build_pipeline.groovy
=> Update docker artifactory url

pipelines/jobs/configurations/jdk21_pipeline_config.groovy
Issue runtimes/infrastructure 8360
=> Update alinux jdk21 to use latest cent7 container

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
related: runtimes/backlog/issues/1099 and https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/175
=> Enable dev.external on plinux

pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk21_pipeline_config.groovy
Related adoptium/ci-jenkins-pipelines#811 runtimes infra 8378
=> Do not hardcode ucrt dll location for Semeru

pipelines/build/dockerFiles/cuda.dockerfile
Related ibmruntimes/temurin-build#94
=> Don't version the cuda install folder

pipelines/build/common/openjdk_build_pipeline.groovy
- Fix docker credential parameter
- Related Issue: https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/185
=> Fix docker credential parameter

pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
=> Enable FIPS140-2 testing for p/z linux for JDK17

pipelines/build/common/openjdk_build_pipeline.groovy
resolves: runtimes/backlog/issues/1351
=> Set jreUrl for special.openjdk

pipelines/jobs/configurations/jdk22.groovy, pipelines/jobs/configurations/jdk22_pipeline_config.groovy
=> Enables Semeru 22 builds

pipelines/build/common/openjdk_build_pipeline.groovy
related: backlog/issues/1353
depends on: osb-tests/pull/44
=> Add internal test repo

pipelines/build/common/openjdk_build_pipeline.groovy
=> Fix logic adding openjceplus bundle arg to env

pipelines/build/common/build_base_file.groovy
=> Do not dry run publish releases

pipelines/build/common/openjdk_build_pipeline.groovy
related: https://github.com/eclipse-openj9/openj9/issues/19122
=> Set smoke tests blocking in release testing only

pipelines/defaults.json
for code housekeeping and move stuff to infra-can main repo.
=> disable EBC temporarily on Semeru pipeline

pipelines/defaults.json
After doing improvements on EBC recipes side, now seems the spinup time is reasonable. So putting it back to see in action
=> restores EBC functionality

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
=> Remove uid1000 label

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk17u_pipeline_config.groovy, pipelines/jobs/configurations/jdk21u_pipeline_config.groovy, pipelines/jobs/configurations/jdk22u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
sets docker image, lables and docker credentials do pull docker image from local docker registery
=> issue_9128 enables rhel7 s390 docker build in semeru pipeline

pipelines/jobs/configurations/jdk11u.groovy
=> Turn off jdk11 riscv build

pipelines/build/common/openjdk_build_pipeline.groovy
- Remove extra ? in fips suffix
- Related to git_ibm/runtimes/infrastructure/issues/9566
=> Remove extra ? in fips suffix

pipelines/build/common/openjdk_build_pipeline.groovy
=> Fix split()

pipelines/build/common/openjdk_build_pipeline.groovy
=> Temporarily not block testing on failed build stages

pipelines/build/common/openjdk_build_pipeline.groovy
=> Do not error out if installer fails

pipelines/build/common/openjdk_build_pipeline.groovy
=> Fix BUILD_LIST for FIPS test builds
