pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk16u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17_pipeline_config.groovy
pipelines/jobs/configurations/jdk8u_pipeline_config.groovy

Update downstream jobs configurations:
- add --with-version* options to configureArgs, update vendor and
product
- remove --with-jdk-rc-name from win8 config
- add special.jck to weekly testing
Update pipeline to support Semeru Certified and Open:
- update upstream job to create separate distribution packages for
Semeru Open and Certified
Add support for Semeru to the downstream jobs:
- update binaries name: replace OpenJDK* with ibm-semeru-*, add
javaToBuild to tarballs names for nightly builds
- remove installer job for Linux, replaced with RPM package pipeline
from upstream job
- replace eclipse-codesign sigh tool with ucl and set node labels for
sign job
- remove directory name from path for checksum files
Update job generator to exclude platforms with additionalFileNameTag.
Update …

Add support for Semeru builds

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/defaults.json

Infer variant version and tag from overridePublishName
and pass them downstream to RPM build.
Fix targets filtering for RPM build.
Add installer repository URL and branch to defaults.json
for scm configuration.

Vary updates for RPM build

---

pipelines/build/prTester/pr_test_pipeline.groovy
pipelines/jobs/configurations/jdk18.groovy
pipelines/jobs/configurations/jdk18_pipeline_config.groovy

Update jdk18 configuration files for upstream and downstream pipelines
for openj9 variant.

Enable Semeru 18

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy
pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/regeneration/build_pipeline_generator.groovy
pipelines/defaults.json
pipelines/jobs/pipeline_job_template.groovy
pipelines/library/src/common/IndividualBuildConfig.groovy

Update upstream and downtream jobs to suport numMachines per test
targets.
Update the job generator to infer the parallel tests flag from job
configuration.
Propagate enableTestDynamicParallel flag downstream.

Add support for numMachine per test for dynamic parallel testing

---

pipelines/build/common/openjdk_build_pipeline.groovy

Fix to ensure Certified bins doesn't get named like Open Edition

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/openjdk_build_pipeline.groovy

Enable installer and installer sign builds for AIX.
Add downstream builds to:
- build the RPM distribution package
- sign the RPM package

Add AIX installer and sign downstream builds

---

pipelines/build/common/build_base_file.groovy
pipelines/build/openjdk_pipeline.groovy
pipelines/build/regeneration/build_pipeline_generator.groovy
pipelines/defaults.json
pipelines/jobs/pipeline_job_template.groovy

Add the following flags to the top pipelines and job generator:
- enableSourceRpm: to launch the source RPM build
- verifySigner: to launch a downstream build to verify if all packages
are signed
Add enable installers, signers and signers verification flags to
pipeline genrator. Remove hardcoded values for flags and infer their
values from defaults.json when not set as build argument.

Add flags to enable/disable srpm and verify sign build

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/create_job_from_template.groovy
pipelines/build/regeneration/build_pipeline_generator.groovy
pipelines/jobs/pipeline_job_template.groovy

Add support for targets exclusion.
Customize job name for upstream pipelines.
Add scm parameters to upstream and downstream jobs.
Allow on demand pipeline generation based on version.
Pass downstream SCM_REPO, SCM_BRANCH, USER_REMOTE_CONFIGS and
DEFAULTS_JSON.

Job generation customization

---

pipelines/jobs/configurations/jdk17u_pipeline_config.groovy

Add --create-jre-image to buildArgs for all Semeru 17 OE platforms.

Enable JRE images for Semeru 17 OE

---

pipelines/build/common/openjdk_build_pipeline.groovy

The way it is currently defined, the last iteration
of the loop will apply to all the tests once they
are executed. Redifining it each loop will ensure
each test gets the correct value.
Related #213

Ensure numMachinesPerTest is reset each loop

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

Related: internal/runtimes/backlog/issues/593

enable sanity.external in p/z/alinux for JDK11

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
pipelines/jobs/configurations/jdk18_pipeline_config.groovy
pipelines/jobs/configurations/jdk8u_pipeline_config.groovy

Moved to build repo sbin/build.sh via
https://github.com/ibmruntimes/temurin-build/pull/10/commits/b19880
Also remove Certified Edition config as it is hardcoded in the ext repo.

Remove vendor config params from job config groovy

---

pipelines/build/common/openjdk_build_pipeline.groovy

listArchives is only used in 2 spots. First when we produce the
Windows jre installer. Second when we create the json metadata.
Therefore I believe it is best to remove the tar.gz.sig case
from this function
Issue ibmruntimes/Semeru-Runtimes#20

Stop producing sig json files

---

pipelines/build/regeneration/build_pipeline_generator.groovy

Should put this param in based on itself not the installer param

Fix variable name typo ENABLE_SOURCE_RPM

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

enable jck and openjdk FIPS testing for JDK11 xlinux weekly runs
Related: runtimes/backlog/issues/758
Depends on: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/520
Depends on: https://github.com/adoptium/aqa-test-tools/pull/655

Add FIPS testing

---

pipelines/jobs/configurations/jdk19_pipeline_config.groovy

Use containers for Linux x86-64 and aarch64 for compilation with gcc7.5
or gcc-10.3.
Clean up ci.project.openj9 (added by default in addition to
ci.role.build.release, see formAdditionalBuildNodeLabels() method).
Set boot-jdk=18 (Temurin 18) as Semeru 19 does not compile with Temurin
19 (the default boot-jdk for JDK19).

Update configuration for JDK19

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
pipelines/jobs/configurations/jdk18_pipeline_config.groovy
pipelines/jobs/configurations/jdk19_pipeline_config.groovy

This commit removes the "--disable-ddr" option from configuration for AArch64 macOS.
Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

AArch64 macOS: Enable DDR builds

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy

Add x64LinuxCRIU platform to JDK17 pipelines.
Clean up configuration for JDK11 pipelines.

Add CRIU support for JDK17 on Linux x86-64

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy

resolves: runtimes/backlog/issues/826
depends on: https://github.com/eclipse-openj9/openj9/pull/15372

enable sanity.functional.fips to run FIPS tests only

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy

Related: runtimes/backlog/issues/878

Enable all functional and sanity.external for CRIU nightly

---

pipelines/build/common/openjdk_build_pipeline.groovy

- Add DOCKER_REGISTRY_URL and DOCKER_REGISTRY_URL_CREDENTIAL_ID
- These two parameters are only needed by External tests
- Related PR: https://github.com/adoptium/aqa-tests/pull/3960
- Related Issue: ibm_github/runtimes/backlog/issues/879
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

Add docker registry parameters for external test

---

pipelines/defaults.json
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

- Enabled dev.system on JDK11 xlinux weekly run
- parallel on 5 machines
Related: backlog/issues/926

Enabled dev.system on JDK11 xlinux

---

pipelines/build/common/create_job_from_template.groovy
pipelines/jobs/pipeline_job_template.groovy

Only used for Adopt farm to block non-temurin builds from public view

Comment out authorizationMatrix

---

pipelines/build/common/openjdk_build_pipeline.groovy

Remove FIPS specific options from Semeru pipeline to aqa-test repo.
This is needed to support FIPS test builds in AQA_Test_Pipeline
Depends on https://github.com/adoptium/aqa-tests/pull/4016
related: backlog/issues/927

Remove FIPS specific options from Semeru pipeline

---

pipelines/build/common/create_job_from_template.groovy
pipelines/jobs/pipeline_job_template.groovy

The changes introduced by #154 #155 are specific
to Adoptium and can cause unwanted behaviour on
other users' Jenkins'. Simple solution to only
run that part of the code on Jenkins' that are
owned by Adopt (have adopt in the URL).
Probably good enough to resolve #156 while we're here.

Only force authorizationMatrix on Adoptium's jenkins

---

pipelines/build/common/openjdk_build_pipeline.groovy

Fixes https://github.com/adoptium/aqa-tests/issues/2097
cc @llxia @sophia-guo @smlambert

setting sdk_resource as customized for runAqaTest

---

pipelines/jobs/configurations/jdk19u.groovy

Enable JDK19 nightly builds
Signed-off-by: Jason Feng <fengj@ca.ibm.com>

Enable JDK19 nightly builds

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy

- Enable dev.external in JDK17 xlinux
- Restrict dev.external on ub22 or rhel8 (i.e., cannot use ub20 for testing)

Enable dev.external in JDK17

---

pipelines/build/common/openjdk_build_pipeline.groovy

Ensures we have a key handy no matter which repo we clone

Use sshagent for all Semeru builds

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

- Enable dev.jck weekly 
- Add geo labels for aix for multijvm tck tests using two nodes.
Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>

Enable dev.jck + add geo labels for aix

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

- Enable dev.jck on IBM xLinux, aLinux, xMac, aMac, x64 Windows
- set ADDITIONAL_ARTIFACTS_REQUIRED=RI_JDK for dev.jck builds 
Related to backlog/issues/1028
Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>

Enable dev.jck for IBM JDK11 on xLinux, aLinux, xMac, aMac, x64 Windows

---

pipelines/build/common/create_job_from_template.groovy
pipelines/jobs/configurations/jdk20.groovy
pipelines/jobs/configurations/jdk20_pipeline_config.groovy

Enable JDK20 builds and tests for Semeru:
- update pipeline configuration
- schedule nightly and weekly builds once a week
Fix refspec in job generator.

Enable Semeru 20 pipelines

---

pipelines/jobs/configurations/jdk11u.groovy
pipelines/jobs/configurations/jdk17u.groovy

Enabled by default on z.
Enabled via build config option on p

Disable separate criu specs for z p linux

---

pipelines/jobs/configurations/jdk19u.groovy
pipelines/jobs/configurations/jdk20u.groovy

Disable JDK19 builds.
Schedule JDK20 builds nightly.

Update build schedule for JDK19 and JDK20

---

pipelines/build/common/openjdk_build_pipeline.groovy

CRIU workflow is updated so that the test pipeline (i.e., dev.external) will handle the image upload and image pull. Remove runUploadTestImage() from Semeru pipeline
Related: https://github.com/adoptium/aqa-tests/issues/4465 and https://github.com/adoptium/aqa-tests/pull/4521

Remove runUploadTestImage()

---

pipelines/build/common/openjdk_build_pipeline.groovy

Due to https://github.com/adoptium/aqa-tests/issues/4465, the test pipeline (i.e., dev.external) will handle the image upload and image pull. We no longer need to set additional label in the build pipeline.

remove additionalTestLabel

---

pipelines/build/common/openjdk_build_pipeline.groovy

By default, RERUN_ITERATIONS=3. Set RERUN_ITERATIONS=0 for any FIPS, external, or dev test builds

enable rerun test builds

---

pipelines/jobs/configurations/jdk20u.groovy
pipelines/jobs/configurations/jdk21.groovy
pipelines/jobs/configurations/jdk21_pipeline_config.groovy

Disable Semeru 20
Issue Infra 8044

Enable Semeru 21 OE and CE

---

pipelines/build/dockerFiles/cuda.dockerfile

also make docker file parametrized with default cuda ver 12.2.0

Revert cuda workaround in Semeru builds

---

pipelines/build/common/openjdk_build_pipeline.groovy

Regarding the CUDA 9.0 end of support, this was a temporary workaround. Now we can use DUDA 12 and we do not need it anymore.
Resolves issue runtimes/infrastructure#8331

Reverts CUDA9 end of support temp workaround 

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy

Now that CRIU is enabled by default on platforms for all versions that support it we can remove configs. Resolves issue#8372

Remove unneeded criu configs

---

pipelines/build/common/openjdk_build_pipeline.groovy

If we're building in a docker container we pull the cuda container during the build process. If we're not logged into a registry we can hit a rate limit.

Wrap build process in withRegistry for Docker builds

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
pipelines/jobs/configurations/jdk21u_pipeline_config.groovy

- BASE_DOCKER_REGISTRY_CREDENTIAL_ID is needed to increase daily image pull limit when running container-based external testing
- Related Issue: runtimes/backlog/issues/1234

Add BASE_DOCKER_REGISTRY_CREDENTIAL_ID for external-test

---

pipelines/build/common/weekly_release_pipeline.groovy

Rather than hardcoding 'Weekly', use the build parameter.

Use parameter releasType to pass to downstream

---

pipelines/jobs/configurations/jdk21u_pipeline_config.groovy

Enable dev.external on aarch64LinuxIBM in JDK21

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/defaults.json

A new flag is added to the `DEFAULTS_JSON` struct to allow for bundling `OpenJCEPlus` with Semeru. Said flag is then potentially propagated to the subsequent scripts. 
The appropriate credentials are, also, used to allow for the required downloading of the `GSKit` binaries.
Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

Bundle OpenJCEPlus and get GSKit binaries from Artifactory

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

Don't run dev level on release.
Don't run external group on release

Add release test lists for jdk11 specs

---

pipelines/jobs/configurations/jdk8u_pipeline_config.groovy

Each list needs to be explicitly defined now.
This was missed.

Add nightly targets to weekly build jdk8

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/defaults.json

A list of Java versions to be excluded from bundling `OpenJCEPlus` with is introduced, in place of the existing boolean value.
Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

Change to exclude list of versions bundling OpenJCEPlus

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/defaults.json

It add a function called allocateEBCnodesForTest which return label for new generated EBC nodes and let test use it.

enables EBC for test inside semeru builds

---

pipelines/build/common/openjdk_build_pipeline.groovy

now sign can only fails build when buildConfig.RELEASE. Otherwise it will only show a warning. https://github.ibm.com/runtimes/infrastructure/issues/9015

issue-9015 prevents build failure if sign failed, in non-release runs

---

pipelines/defaults.json

it disables EBC temporarily in pipeline in order to test new features and do some maitenance.

disables EBC in pipeline

---

pipelines/defaults.json

After the issue with registering EBC nodes resolved now we can enable back the sanity.perf in semeru build pipelines.

enables sanity.perf in x64 linux for EBC

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
pipelines/jobs/configurations/jdk21u_pipeline_config.groovy
pipelines/jobs/configurations/jdk22_pipeline_config.groovy

Enable 140-3_OpenJCEPlusFIPS sanity.openjdk and extended.openjdk on xlinux, plinux, zlinux and AIX on JDK11/17/21/22.
related: backlog/issues/1450

Add support for FIPS140-3

---

pipelines/build/common/openjdk_build_pipeline.groovy

It let all all docker images to be pulled not only rhel7
Signed-off-by: mahdi@ib.com

issue_9128 removes condition which only let rhel7 to be pulled

---

pipelines/build/common/openjdk_build_pipeline.groovy

while working with non-default docker registry, the local image tag will be DOCKER_REGISTRY+DOCKER_IMAGE. This change will add a tag with DOCKER_IMAGE only then the rest of pipeline witch works with DOCKER_IMAGE will not fail. Also it improves fetching .RepoDigests so do not need `dockerImageDigest = dockerImageDigest.replaceAll("\\[", "").replaceAll("\\]", "")` anymore
Signed-off-by: mahdi@ibm.com

issue_9128 solves issue working with non-default docker registries

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk17u_pipeline_config.groovy
pipelines/jobs/configurations/jdk21u_pipeline_config.groovy
pipelines/jobs/configurations/jdk22u_pipeline_config.groovy
pipelines/jobs/configurations/jdk8u_pipeline_config.groovy

It separates docker registery from docker image and prevents from login to default registery on z-builds which image stored in local artifactory.
Signed-off-by: mahdi@ibm.com

issue_9128 resolves the issue with login to wrong docker registery

---

pipelines/build/common/openjdk_build_pipeline.groovy

the code improvement caused issue on images who do not have RepoDigests when asked for index 0. It reverts the changes back to avoid issue.
Signed-off-by: mahdi@ibm.com

issue_9554 revert code improvments fetch dockerImageDigest

---

pipelines/jobs/configurations/jdk22u_pipeline_config.groovy
pipelines/jobs/configurations/jdk23.groovy
pipelines/jobs/configurations/jdk23_pipeline_config.groovy

Copied from jdk22 configs. Will keep same schedule since we will be disabling 22.

Enable jdk23 semeru builds

---

pipelines/build/common/openjdk_build_pipeline.groovy

resovles: automation/issues/103

Fix vendor repo missing issue for regular test builds
